name: fluxoComAmbiente
on: 
  workflow_dispatch:

jobs:
  build:
     runs-on: ubuntu-latest
     steps:
      - name: Build
        run: echo construindo aplicação
  
  deploy-dev:
     runs-on: ubuntu-latest
     environment:
       name: developer
     needs: build 
     steps:
      - name: developer
        run: echo analisando feature
        
  deploy-testes:
     runs-on: ubuntu-latest
     environment:
       name: testes
       url: 'http://www.google.com'
     needs: deploy-dev  
     steps:
      - name: testes
        run: echo testando codigo....
   
  deploy-homolog:
     runs-on: ubuntu-latest
     environment:
       name: homolog
       url: 'http://www.google.com'
     needs: deploy-dev  
     steps:
      - name: testes
        run: echo testando codigo....
  
  deploy-producao:
     runs-on: ubuntu-latest
     environment:
       name: producao
     needs: deploy-homolog  
     steps:
      - name: homolog
        run: echo homologando....
     
