name: fluxoComAmbiente
on: 
  workflow_dispatch:

jobs:
  build:
     runs-on: ubuntu-latest
     steps:
      - name: Build
        run: echo construindo aplicação
  
  deploy-dev:
     runs-on: ubuntu-latest
     environment:
       name: developer
     needs: build 
     steps:
      - name: developer
        run: echo analisando feature
        
  deploy-homolog:
     runs-on: ubuntu-latest
     environment:
       name: homolog
     needs: deploy-dev  
     steps:
      - name: homolog
        run: echo aanlisando codigo....
        
  deploy-producao:
     runs-on: ubuntu-latest
     environment:
       name: producao
     needs: deploy-homolog  
     steps:
      - name: homolog
        run: echo homologando....
     
